Repository roundcube/roundcubemail, pull requests merged in 2020-01, with the labels that each got.

#6789 Improve namespace roots presentation (#5012)
  program/include/rcmail.php
  program/lib/Roundcube/rcube_imap.php
  skins/elastic/styles/widgets/lists.less
Labels: C: User Interface, enhancement

#6772 add support for SameSite cookie attribute
  config/defaults.inc.php
  program/lib/Roundcube/rcube.php
  program/lib/Roundcube/rcube_utils.php
Labels: C: Framework, C: User Interface, enhancement

#6763 Managesieve: Allow display name with email address in vacation :from field (#6760)
  plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
  plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php
Labels: C: Plugins, C: User Interface, enhancement

#7169 Remove recipient duplicates in print-view when the recipient list is expanded
  program/steps/mail/func.inc
Labels: C: User Interface, bug

#7181 Fix creation of pgp-keys for IDN emails
  plugins/enigma/lib/enigma_ui.php
Labels: C: Encryption, C: Plugins, bug
